version: "3.9"
services:

  people:
    ports:
      - "8080:8080"
    build: .
    depends_on:
      - postgres

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "people"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    image: postgres:13.1
